In [39]:
import pandas as pd

## Load CSV File

In [40]:
movies=pd.read_csv("D:\personal\ConsoleFlare\pd\DATA SET\ml-25m\ml-25m\movies.csv")

In [41]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
20,21,Get Shorty (1995),Comedy|Crime|Thriller
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
22,23,Assassins (1995),Action|Crime|Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Children|Drama
27,28,Persuasion (1995),Drama|Romance
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
...,...,...,...
62393,209067,Sousse: Marché aux charbons (avec chameaux) (1...,(no genres listed)
62394,209069,Snapshots (2002),Drama|Romance
62395,209073,The Arbalest (2016),Drama
62396,209075,Monkey Love Experiments (2014),Animation|Drama
62397,209079,Call of Cuteness (2017),Animation
62398,209085,The Mistletoe Secret (2019),Romance
62399,209089,An Impossible Balancing Feat (1902),(no genres listed)
62400,209101,Hua yang de nian hua (2001),(no genres listed)
62401,209103,Tsar Ivan the Terrible (1991),(no genres listed)
62402,209119,Up to the World (2014),Comedy|Drama
62403,209121,Adrenalin: The BMW Touring Car Story (2014),Documentary
62404,209123,Square Roots: The Story of SpongeBob SquarePan...,Documentary
62405,209129,Destination Titan (2011),Documentary
62406,209131,Last Days of the Arctic (2011),Documentary
62407,209133,The Riot and the Dance (2018),(no genres listed)
62408,209135,Jane B. by Agnès V. (1988),Documentary|Fantasy
62409,209137,The Reward's Yours... The Man's Mine (1969),Western
62410,209139,Rimsky-Korsakov (1953),Drama
62411,209141,And They Lived Happily Ever After (1976),Comedy
62412,209143,The Painting (2019),Animation|Documentary
62413,209145,Liberté (2019),Drama
62414,209147,The Carpet of Horror (1962),Crime|Horror
62415,209151,Mao Zedong 1949 (2019),(no genres listed)
62416,209153,Happy Flight (2008),Comedy|Drama
62417,209155,Santosh Subramaniam (2008),Action|Comedy|Romance
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [42]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [43]:
movies.sample(n=3)

       movieId                 title    genres
25348   123524        Untamed (1929)     Drama
25220   123252      I Accuse! (1958)     Drama
31074   137688  Escape Clause (1996)  Thriller

In [44]:
movies.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [45]:
movies.tail()

       movieId                           title                  genres
62418   209157                       We (2018)                   Drama
62419   209159       Window of the Soul (2001)             Documentary
62420   209163                Bad Poems (2018)            Comedy|Drama
62421   209169             A Girl Thing (2001)      (no genres listed)
62422   209171  Women of Devil's Island (1962)  Action|Adventure|Drama

In [46]:
movies.tail(3)

       movieId                           title                  genres
62420   209163                Bad Poems (2018)            Comedy|Drama
62421   209169             A Girl Thing (2001)      (no genres listed)
62422   209171  Women of Devil's Island (1962)  Action|Adventure|Drama

In [47]:
type(movies)

pandas.core.frame.DataFrame

In [48]:
movies.shape

(62423, 3)

In [49]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [50]:
movies.size

187269

## Exprting Csv

In [51]:
movies.to_csv('movies.csv',index=False,header=True)

In [53]:
pd.options.display.max_rows=10

In [54]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama